[formatter.gofmt]
command = "gofmt"
options = [ "-w" ]
includes = [ "*.go" ]

[formatter.gofumpt]
command = "gofumpt"
options = [ "-w" ]
includes = [ "*.go" ]

[formatter.goimports]
command = "goimports"
options = [ "-w" ]
includes = [ "*.go" ]
